#
#  Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       Fraunhofer IEE - initial API and implementation
#
#

install:
  mongodb: true

global:
  defaultStorageClass: default
  secrets:
    mongo:
      secretName: mongodb-secret
      keys:
        - mongodb-root-password
        - mongodb-passwords

namespaceOverride: ""

registry:
  unregisterTimeout: 60
  image:
    repository: ghcr.io/re4de/connector-registry
    tag: 1.0.0-edc0.14.0
  service:
    port: 3000
  ingress:
    enabled: true
    host: changeme
    path: /api
  auth:
    apiKey: changeme
  database:
    host: null
    port: 27017
    username: connector-registry
    dbName: registry
    existingSecret: mongodb-secret

mongodb:
  image:
    repository: bitnamilegacy/mongodb
  useStatefulSet: true
  replicaSetHostnames: false
  auth:
    existingSecret: mongodb-secret
    usernames:
      - connector-registry
    databases: 
      - registry
  replicaCount: 1
  pdb:
    create: false
  persistence:
    name: mongo-vol
    resourcePolicy: keep
  arbiter:
    enabled: false