{{/*
Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)

This program and the accompanying materials are made available under the
terms of the Apache License, Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0

SPDX-License-Identifier: Apache-2.0

Contributors:
     Fraunhofer IEE - initial API and implementation
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.name" . }}
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels" . | nindent 8 }}
    spec:
      containers:
        - name: connector-registry
          image: {{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}
          imagePullPolicy: Always
          env:
            - name: PORT
              value: {{ .Values.registry.service.port | quote }}
            - name: API_PREFIX
              value: {{ .Values.registry.ingress.path | quote }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: registry-secret
                  key: api-key
            - name: MONGO_HOST
              value: {{ ternary .Values.registry.database.host (printf "%s-mongodb" .Release.Name) (not .Values.install.mongodb) }}
            - name: MONGO_PORT
              value: {{ .Values.registry.database.port | quote }}
            - name: MONGO_USER
              value: {{ .Values.registry.database.username | quote }}
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.registry.database.existingSecret }}
                  key: {{ (index .Values.mongodb.customUsers 0).secretKeys.password }}
            - name: MONGO_DB_NAME
              value: {{ .Values.registry.database.dbName | quote }}
            - name: REGISTRY_UNREGISTER_TIMEOUT
              value: {{ .Values.registry.unregisterTimeout | quote }}
            